---
# install freckles using conda, assuming the conda package manager is already installed

- name: find conda binary
  get_conda_facts:
    conda_binary: "{{ conda_binary_name }}"

- name: check conda environments
  command: "{{ conda_path }}"
