---
# tasks file for install-freckles
- name: "[fail if wrong install method specified]"
  fail:
    msg: "'install_method' variable needs to be either 'auto', 'conda' or 'pip'"
  when: "install_method not in ['auto', 'conda', 'pip']"

- name: "[finding freckles binary]"
  get_conda_facts:
    conda_binary: "{{ conda_binary_name }}"
    freckles_binary: "{{ freckles_binary_name }}"
    install_method: "{{ install_method }}"
  become: no

- include: conda.yml
  when: "install_method == 'conda' or existing_install_method == 'conda' or (not freckles_binary_path and install_method == 'auto')"

- include: non-conda.yml
  when: "install_method == 'pip' or existing_install_method == 'pip'"

- name: installing freckles
  pip:
    name: freckles
    executable: "{{ pip_to_use }}"
    extra_args: "{{ extra_pip_args }}"
  become: no
  when: "not freckles_exists"

- name: updating freckles
  pip:
    name: freckles
    executable: "{{ pip_to_use }}"
    extra_args: "--upgrade-strategy only-if-needed {{ extra_pip_args }} -U"
  become: no
  when: update
