---
# tasks file for install-freckles

- include: conda.yml
  when: use_conda

- include: non-conda.yml
  when: not use_conda

- name: install freckles
  pip:
    name: freckles
    executable: "{{ pip_to_use }}"
    extra_args: "{{ extra_pip_args }}"
  become: no
  when: not freckles_exists

- name: update freckles
  pip:
    name: freckles
    executable: "{{ pip_to_use }}"
    extra_args: "--upgrade-strategy only-if-needed {{ extra_pip_args }} -U"
  become: no
  when: update
